stages:
  preprocess:
    cmd: python -m ostram compile-inputs
    deps:
      - ostram/pipeline/compilation/
      - config/compilation/Config_MOMF_T1_A.yaml
      - workspace/preparation/A1_Outputs/
      - workspace/preparation/extra_inputs/
    outs:
      - workspace/compilation/A2_Structure_Lists.xlsx
      - workspace/compilation/A2_Output_Params/

  executing:
    cmd: python -m ostram run --skip-a3 --skip-b1
    deps:
      - ostram/pipeline/execution/
      - ostram/resources/compilation/
      - config/execution/Config_MOMF_T1_AB.yaml
      - model/osemosys_fast_preprocessed.txt
      - workspace/compilation/A2_Output_Params/
    outs:
      - workspace/execution/A2_Outputs_Params_otoole/:
          cache: false
          persist: true
      - workspace/execution/Executables/:
          cache: false
          persist: true
      - workspace/execution/Outputs/:
          cache: false
          persist: true
