"""Declared restriction-materialization prerequisites.

A registry may declare that one root's Restrictions rows are generated by
another root (``{"type": "restrictions", "scenario": ...}``).  The declared
prerequisite widens A3 materialization and snapshot checking only; the
downstream B1/B2/reporting selection stays exactly what the user requested.
"""

from __future__ import annotations

import io
import json
import os
import shutil
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest import mock

from openpyxl import Workbook, load_workbook

from ostram.pipeline.scenarios import materializer as materializer_module
from ostram.pipeline.scenarios import transform as transform_module
from ostram.pipeline.scenarios.materializer import (
    MaterializationPaths,
    REQUIRED_AO_FILES,
    materialize_scenarios,
    validate_control_roots,
)
from ostram.pipeline.scenarios.registry import load_registry

from tests.regression.test_run_orchestration import (
    LauncherHarness,
    _load_launcher,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
UNESCAP_REGISTRY = (
    REPO_ROOT / "examples" / "unescap" / "config" / "scenarios" / "registry.json"
)
UNESCAP_WORKBOOK = (
    REPO_ROOT / "examples" / "unescap" / "inputs" / "scenarios"
    / "OSTRAM_Scenario_Inputs.xlsx"
)
PREPARATION_WORKSPACE = REPO_ROOT / "workspace" / "preparation"


def _write_registry(root: Path, root_scenarios: list[dict]) -> Path:
    registry_path = root / "registry.json"
    registry_path.write_text(
        json.dumps(
            {
                "schema": "ostram-scenario-registry-v1",
                "support_scenarios": [root_scenarios[0]["name"]],
                "root_scenarios": root_scenarios,
                "decision_scenarios": [
                    entry["name"]
                    for entry in root_scenarios
                    if entry["role"] == "decision"
                ],
                "derived_scenarios": [],
            }
        ),
        encoding="utf-8",
    )
    return registry_path


def _root(name: str, role: str, restrictions: list[str] | None = None) -> dict:
    return {
        "name": name,
        "role": role,
        "dependencies": [
            {"type": "restrictions", "scenario": scenario}
            for scenario in (restrictions or [])
        ],
    }


class RestrictionDependencyContractTests(unittest.TestCase):
    def test_unescap_registry_declares_the_bau_prerequisite_for_a(self) -> None:
        registry = load_registry(UNESCAP_REGISTRY)
        roots = registry.roots_by_name
        self.assertEqual(
            roots["A_Calibrated_BAU"].restriction_dependencies,
            ("BAU",),
        )
        for name in ("BAU", "B_Optimised_VRE", "C_Target_VRE"):
            self.assertEqual(roots[name].restriction_dependencies, ())
        # The C result dependency is a separate contract and stays intact.
        self.assertEqual(
            [dep.scenario for dep in roots["C_Target_VRE"].dependencies],
            ["A_Calibrated_BAU"],
        )

    def test_full_registry_declares_no_restriction_prerequisites(self) -> None:
        registry = load_registry()
        for root in registry.roots:
            self.assertEqual(root.restriction_dependencies, ())
        self.assertEqual(
            registry.required_roots(registry.select("A_Calibrated_BAU")),
            ("A_Calibrated_BAU",),
        )

    def test_selection_expansion_matches_the_declared_contract(self) -> None:
        registry = load_registry(UNESCAP_REGISTRY)
        cases = (
            ("A_Calibrated_BAU", ("A_Calibrated_BAU",),
             ("BAU", "A_Calibrated_BAU")),
            ("A_Calibrated_BAU,B_Optimised_VRE",
             ("A_Calibrated_BAU", "B_Optimised_VRE"),
             ("BAU", "A_Calibrated_BAU", "B_Optimised_VRE")),
            ("B_Optimised_VRE", ("B_Optimised_VRE",), ("B_Optimised_VRE",)),
            ("BAU", ("BAU",), ("BAU",)),
            ("BAU,A_Calibrated_BAU", ("BAU", "A_Calibrated_BAU"),
             ("BAU", "A_Calibrated_BAU")),
        )
        for requested, downstream, materialized in cases:
            with self.subTest(requested=requested):
                selected = registry.select(requested)
                self.assertEqual(selected, downstream)
                self.assertEqual(registry.required_roots(selected), materialized)

    def test_transitive_expansion_is_deduplicated_and_canonical(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            registry = load_registry(
                _write_registry(
                    Path(temp),
                    [
                        _root("Base", "support"),
                        _root("Mid", "decision", ["Base"]),
                        _root("Leaf", "decision", ["Mid"]),
                    ],
                )
            )
            self.assertEqual(
                registry.required_roots(("Leaf",)),
                ("Base", "Mid", "Leaf"),
            )
            self.assertEqual(
                registry.required_roots(("Mid", "Leaf")),
                ("Base", "Mid", "Leaf"),
            )
            self.assertEqual(registry.required_roots(("Base",)), ("Base",))

    def test_invalid_declarations_are_rejected(self) -> None:
        cases = (
            (
                "unknown",
                [_root("Base", "support"), _root("Leaf", "decision", ["Ghost"])],
                "unknown root Ghost",
            ),
            (
                "self",
                [_root("Base", "support"), _root("Leaf", "decision", ["Leaf"])],
                "dependency on itself",
            ),
            (
                "cyclic",
                [
                    _root("Base", "support"),
                    _root("Mid", "decision", ["Leaf"]),
                    _root("Leaf", "decision", ["Mid"]),
                ],
                "must precede",
            ),
            (
                "reversed-order",
                [
                    _root("Base", "support", ["Leaf"]),
                    _root("Leaf", "decision"),
                ],
                "must precede",
            ),
            (
                "duplicate",
                [
                    _root("Base", "support"),
                    _root("Leaf", "decision", ["Base", "Base"]),
                ],
                "duplicate restriction dependencies",
            ),
            (
                "unnamed",
                [
                    _root("Base", "support"),
                    {
                        "name": "Leaf",
                        "role": "decision",
                        "dependencies": [{"type": "restrictions"}],
                    },
                ],
                "must name a scenario",
            ),
            (
                "unsupported-type",
                [
                    _root("Base", "support"),
                    {
                        "name": "Leaf",
                        "role": "decision",
                        "dependencies": [{"type": "mystery"}],
                    },
                ],
                "unsupported dependency type",
            ),
        )
        for label, root_scenarios, message in cases:
            with self.subTest(label=label):
                with tempfile.TemporaryDirectory() as temp:
                    registry_path = _write_registry(Path(temp), root_scenarios)
                    with self.assertRaisesRegex(ValueError, message):
                        load_registry(registry_path)

    def test_declared_prerequisite_must_agree_with_workbook_control(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            disagreeing = load_registry(
                _write_registry(
                    Path(temp),
                    [
                        _root("BAU", "support"),
                        _root("A_Calibrated_BAU", "decision", ["BAU"]),
                        # Control declares no inheritance for B.
                        _root("B_Optimised_VRE", "decision", ["BAU"]),
                        _root("C_Target_VRE", "decision"),
                    ],
                )
            )
            with self.assertRaisesRegex(
                ValueError,
                r"B_Optimised_VRE are not declared by Control",
            ):
                validate_control_roots(disagreeing, UNESCAP_WORKBOOK)

        # The committed UNESCAP declaration agrees with its Control sheet.
        validate_control_roots(load_registry(UNESCAP_REGISTRY), UNESCAP_WORKBOOK)


class RestrictionPrerequisiteMaterializationTests(unittest.TestCase):
    def test_a_selection_materializes_bau_first_and_keeps_selection(self) -> None:
        registry = load_registry(UNESCAP_REGISTRY)
        with tempfile.TemporaryDirectory() as temp:
            outputs = Path(temp) / "A1_Outputs"
            for root in ("BAU", "A_Calibrated_BAU"):
                snapshot = outputs / f"_post_a2_snapshot_{root}"
                snapshot.mkdir(parents=True)
                for filename in REQUIRED_AO_FILES:
                    (snapshot / filename).write_bytes(b"fixture")

            paths = MaterializationPaths(
                preparation_workspace=PREPARATION_WORKSPACE,
                a1_outputs=outputs,
                a3_entrypoint=(
                    REPO_ROOT / "ostram" / "pipeline" / "scenarios" / "transform.py"
                ),
                a3_process=(
                    REPO_ROOT / "ostram" / "pipeline" / "scenarios"
                    / "transformations"
                ),
                soasia=UNESCAP_WORKBOOK,
            )
            materialized: list[str] = []

            def materialize_root(root: str, environment: dict[str, str]) -> None:
                del environment
                materialized.append(root)
                shutil.copytree(
                    outputs / f"_post_a2_snapshot_{root}",
                    outputs / f"A1_Outputs_{root}",
                )

            record = materialize_scenarios(
                ("A_Calibrated_BAU",),
                paths=paths,
                registry=registry,
                environment=dict(os.environ),
                root_materializer=materialize_root,
                direction_applier=lambda *_: {},
            )

        self.assertEqual(materialized, ["BAU", "A_Calibrated_BAU"])
        self.assertEqual(record["selected_scenarios"], ["A_Calibrated_BAU"])
        self.assertEqual(record["required_roots"], ["BAU", "A_Calibrated_BAU"])
        self.assertFalse(record["solver_invoked"])

    def test_missing_prerequisite_snapshot_fails_closed(self) -> None:
        registry = load_registry(UNESCAP_REGISTRY)
        with tempfile.TemporaryDirectory() as temp:
            outputs = Path(temp) / "A1_Outputs"
            snapshot = outputs / "_post_a2_snapshot_A_Calibrated_BAU"
            snapshot.mkdir(parents=True)
            paths = MaterializationPaths(
                preparation_workspace=PREPARATION_WORKSPACE,
                a1_outputs=outputs,
                a3_entrypoint=(
                    REPO_ROOT / "ostram" / "pipeline" / "scenarios" / "transform.py"
                ),
                a3_process=(
                    REPO_ROOT / "ostram" / "pipeline" / "scenarios"
                    / "transformations"
                ),
                soasia=UNESCAP_WORKBOOK,
            )
            with self.assertRaisesRegex(FileNotFoundError, r"\['BAU'\]"):
                materialize_scenarios(
                    ("A_Calibrated_BAU",),
                    paths=paths,
                    registry=registry,
                    environment=dict(os.environ),
                    root_materializer=lambda *_: None,
                    direction_applier=lambda *_: {},
                )


def _restrictions_row(scenario: str, tech: str, value: float) -> list:
    return [
        scenario, "Secondary Techs", tech,
        "TotalAnnualMaxCapacityInvestment", 2025, value, "lid_rule", "fixture",
    ]


def _restrictions_workbook(path: Path, rows: list[list]) -> None:
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Restrictions"
    sheet.append([
        "scenario", "source_sheet", "tech", "parameter", "year",
        "value", "rule_applied", "source_run_timestamp",
    ])
    for row in rows:
        sheet.append(row)
    workbook.save(path)


class RunStateHandoffTests(unittest.TestCase):
    def test_restriction_source_parsing_is_fail_closed(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            workspace = Path(temp) / "workspace"
            workspace.mkdir()
            state = workspace / "state.xlsx"
            state.write_bytes(b"fixture")
            parsed = transform_module._parse_restriction_sources(
                [f"BAU={state}"], workspace=workspace
            )
            self.assertEqual(parsed, {"BAU": state})
            self.assertEqual(
                transform_module._parse_restriction_sources(None, workspace=workspace), {}
            )
            outside = Path(temp) / "outside.xlsx"
            outside.write_bytes(b"fixture")
            empty = workspace / "empty.xlsx"
            empty.touch()
            for invalid in (
                ["BAU"],
                ["=missing-scenario"],
                ["BAU="],
                [f"BAU={state}", f"BAU={state}"],
                [f"BAU={workspace / 'absent.xlsx'}"],
                [f"BAU={outside}"],
                [f"BAU={empty}"],
            ):
                with self.subTest(invalid=invalid):
                    with self.assertRaises(SystemExit):
                        transform_module._parse_restriction_sources(
                            invalid, workspace=workspace
                        )

            self.assertEqual(
                transform_module._workspace_run_state_destination(
                    workspace / "state.xlsx", workspace=workspace
                ),
                state,
            )
            for destination in (outside, workspace / "state.csv"):
                with self.subTest(destination=destination):
                    with self.assertRaises(SystemExit):
                        transform_module._workspace_run_state_destination(
                            destination, workspace=workspace
                        )

    def test_stage_4_5_reads_prerequisite_rows_from_exported_state(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            soasia = root / "soasia.xlsx"
            _restrictions_workbook(soasia, [])
            state = root / "_run_state_BAU.xlsx"
            _restrictions_workbook(state, [_restrictions_row("BAU", "T1", 1.5)])
            s5 = root / "stage5"
            s5.mkdir()
            parametrization = Workbook()
            sheet = parametrization.active
            sheet.title = "Secondary Techs"
            sheet.append(["Tech", "Parameter", 2025])
            sheet.append(["T1", "TotalAnnualMaxCapacityInvestment", 9999])
            parametrization.save(s5 / "A-O_Parametrization.xlsx")

            # Header-only authority alone stays fail-closed.
            with self.assertRaisesRegex(ValueError, "No Restrictions rows"):
                transform_module.stage_4_5_apply_inherited_restrictions(
                    s5, soasia, ["BAU"]
                )

            # A source for a scenario outside inherit_from is rejected.
            with self.assertRaises(SystemExit):
                transform_module.stage_4_5_apply_inherited_restrictions(
                    s5, soasia, ["BAU"],
                    restriction_sources={"Other": state},
                )

            transform_module.stage_4_5_apply_inherited_restrictions(
                s5, soasia, ["BAU"],
                restriction_sources={"BAU": state},
            )
            workbook = load_workbook(
                s5 / "A-O_Parametrization.xlsx", data_only=True
            )
            self.assertEqual(
                workbook["Secondary Techs"].cell(row=2, column=3).value,
                1.5,
            )
            workbook.close()

    def _wired_materialization(self, *, export_state: bool, empty_state: bool = False):
        registry = load_registry(UNESCAP_REGISTRY)
        commands: list[list[str]] = []

        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            outputs = root / "A1_Outputs"
            for name in ("BAU", "A_Calibrated_BAU"):
                snapshot = outputs / f"_post_a2_snapshot_{name}"
                snapshot.mkdir(parents=True)
                for filename in REQUIRED_AO_FILES:
                    (snapshot / filename).write_bytes(b"fixture")
            paths = MaterializationPaths(
                preparation_workspace=PREPARATION_WORKSPACE,
                a1_outputs=outputs,
                a3_entrypoint=(
                    REPO_ROOT / "ostram" / "pipeline" / "scenarios"
                    / "transform.py"
                ),
                a3_process=(
                    REPO_ROOT / "ostram" / "pipeline" / "scenarios"
                    / "transformations"
                ),
                soasia=UNESCAP_WORKBOOK,
            )

            def fake_run(command, *, cwd, env, check):
                del cwd, env, check
                arguments = [str(token) for token in command]
                commands.append(arguments)
                scenario = arguments[arguments.index("--scenario") + 1]
                if export_state and "--run-state-out" in arguments:
                    state = Path(
                        arguments[arguments.index("--run-state-out") + 1]
                    )
                    state.parent.mkdir(parents=True, exist_ok=True)
                    state.write_bytes(b"" if empty_state else b"fixture-state")
                target = outputs / f"A1_Outputs_{scenario}"
                shutil.copytree(
                    outputs / f"_post_a2_snapshot_{scenario}", target
                )

            with (
                mock.patch.dict(
                    os.environ,
                    {"OSTRAM_WORKSPACE": str(root / "workspace")},
                    clear=False,
                ),
                mock.patch.object(
                    materializer_module.subprocess, "run", fake_run
                ),
            ):
                record = materialize_scenarios(
                    ("A_Calibrated_BAU",),
                    paths=paths,
                    registry=registry,
                    environment=dict(os.environ),
                    direction_applier=lambda *_: {},
                )
            state_dir = (
                root / "workspace" / "scenarios" / "_restriction_states"
            )
            return commands, record, state_dir.exists()

    def test_default_boundary_wires_the_run_state_handoff(self) -> None:
        commands, record, state_dir_exists = self._wired_materialization(
            export_state=True
        )
        self.assertEqual(
            [cmd[cmd.index("--scenario") + 1] for cmd in commands],
            ["BAU", "A_Calibrated_BAU"],
        )
        bau_command, a_command = commands
        self.assertIn("--run-state-out", bau_command)
        self.assertNotIn("--restrictions-source", bau_command)
        state = bau_command[bau_command.index("--run-state-out") + 1]
        self.assertIn("--restrictions-source", a_command)
        self.assertEqual(
            a_command[a_command.index("--restrictions-source") + 1],
            f"BAU={state}",
        )
        self.assertNotIn("--run-state-out", a_command)
        self.assertEqual(
            record["restriction_prerequisites"],
            {"A_Calibrated_BAU": ["BAU"]},
        )
        self.assertFalse(state_dir_exists)

    def test_missing_exported_state_fails_closed(self) -> None:
        with self.assertRaisesRegex(FileNotFoundError, "nonempty run state"):
            self._wired_materialization(export_state=False)

    def test_empty_exported_state_fails_closed_and_is_cleaned(self) -> None:
        with self.assertRaisesRegex(FileNotFoundError, "nonempty run state"):
            self._wired_materialization(export_state=True, empty_state=True)


class RestrictionPrerequisiteOrchestrationTests(unittest.TestCase):
    def _run(self, requested: str) -> LauncherHarness:
        label = requested.replace(",", "_")
        launcher = _load_launcher(f"restriction_prerequisites_{label}")
        registry = load_registry(UNESCAP_REGISTRY)
        with (
            LauncherHarness(launcher) as harness,
            mock.patch.object(launcher, "load_registry", lambda: registry),
            mock.patch.object(
                sys,
                "argv",
                ["python -m ostram run", "--skip-pull", "--scenarios", requested],
            ),
            redirect_stdout(io.StringIO()),
        ):
            launcher.main()
        return harness

    def test_snapshot_gate_expands_but_downstream_stages_do_not(self) -> None:
        cases = (
            (
                "A_Calibrated_BAU",
                ("BAU", "A_Calibrated_BAU"),
                "A_Calibrated_BAU",
            ),
            (
                "A_Calibrated_BAU,B_Optimised_VRE",
                ("BAU", "A_Calibrated_BAU", "B_Optimised_VRE"),
                "A_Calibrated_BAU,B_Optimised_VRE",
            ),
            (
                "B_Optimised_VRE",
                ("B_Optimised_VRE",),
                "B_Optimised_VRE",
            ),
            (
                "BAU,A_Calibrated_BAU",
                ("BAU", "A_Calibrated_BAU"),
                "BAU,A_Calibrated_BAU",
            ),
        )
        for requested, expected_roots, downstream in cases:
            with self.subTest(requested=requested):
                harness = self._run(requested)
                snapshot = next(
                    event for event in harness.events
                    if event[0] == "snapshot_exists"
                )
                self.assertEqual(snapshot[2], expected_roots)
                # A3 receives the exact user selection; the materializer
                # expands the declared prerequisite internally.
                self.assertEqual(
                    [event[3] for event in harness.events if event[0] == "a3"],
                    downstream.split(","),
                )
                self.assertEqual(
                    [
                        event[3]
                        for event in harness.events
                        if event[0] == "pipeline"
                    ],
                    [
                        ["--scenarios", downstream],
                        ["--scenarios", downstream],
                    ],
                )


if __name__ == "__main__":
    unittest.main()
